### PR TITLE
apply settings to targeted platforms

### PR DESCRIPTION
**Pull request by MasseGuillaume**

### CODE REVIEW

**Comment by MasseGuillaume** [comment]
@sjrd haha I know. That's why it's good to test in the wild before :).

**Comment by densh** [comment]
@MasseGuillaume I've restarted the CI but it's still failing.

**Comment by MasseGuillaume** [comment]
@densh caching issue, it's only failing on macosx. We should not cache ~/.ivy/cache for SNAPSHOT.

**Comment by densh** [comment]
LGTM!

**Pull request merged**
